on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: myimage:latest
          load: true
      -
        name: prepare the service account key file
        run: 'echo "$GCLOUD_KEY_FILE" > $HOME/key-file.json'
        shell: bash
        env:
          GCLOUD_KEY_FILE: ${{secrets.GCLOUD_KEY_FILE}}
      -
        name: Load image
        run: |
          docker run -v /usr/key-file.json:$HOME/key-file.json \
                    -e BUCKET_NAME=$BUCKET_NAME \
                    myimage \
                    /run/deploy.sh
        shell: bash
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
