on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to build and run an image
    steps:
      # To use this repository's private action,
      # you must check out the repository

      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: export DOCKER_BUILDKIT=0; export COMPOSE_DOCKER_CLI_BUILD=0
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: my_registry:${{ github.run_number }}
          cache-from: |
            type=registry,ref=my_registry:cache
          cache-to: |
            type=registry,ref=my_registry:cache,mode=max
          outputs: type=docker,dest=./myimage.tar
      # - name: run
      #   run: |
      #     docker load --input ./myimage.tar
      #     docker run my_registry:${{ github.run_number }}

